services:
  backend:
    build: ./backend
    container_name: youtube-summarizer-backend
    ports:
      - "8008:8008"
    volumes:
      # Persist content directories
      - ./content:/app/content
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: youtube-summarizer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8008
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
