services:
  frontend:
    image: gitmonke/youtube-summarizer-frontend:latest
    container_name: youtube-summarizer-frontend
    ports: ["8009:80"]
    depends_on: [backend]
    networks: [appnet]

  backend:
    image: gitmonke/youtube-summarizer-backend:latest
    container_name: youtube-summarizer-backend
    volumes:
      - backend-content:/app/content
    ports: ["8008:8008"]
    networks: [appnet]

networks:
  appnet:
    driver: bridge

volumes:
  backend-content:
