services:
  frontend:
    image: gitmonke/youtube-summarizer-frontend:latest
    container_name: youtube-summarizer-frontend
    ports: ["8009:8009"]
    depends_on: [backend]
    networks: [appnet]

  backend:
    image: gitmonke/youtube-summarizer-backend:latest
    runtime: nvidia
    container_name: youtube-summarizer-backend
    volumes:
      - backend-content:/app/content
    ports: ["8008:8008"]
    networks: [appnet]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  appnet:
    driver: bridge

volumes:
  backend-content:
